name: Permission Check
on:
  push:
    branches: [master]

jobs:
  check_permissions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Verify Permissions
        run: |
          TOKEN="${{ github.token }}"
          REPO="${{ github.repository }}"
          PERMISSION=$(curl -s -H "Authorization: Bearer $TOKEN" \
            "https://api.github.com/repos/$REPO" | jq -r '.permissions.contents')
          if [ "$PERMISSION" != "read" ]; then
            echo "Error: Expected permissions, got: $PERMISSION"
            exit 1
          fi
          echo "Permission check passed"
